### PR TITLE
Fix incorrect index in fix_nonadvective_mosaic

### PR DESCRIPTION
**Pull request by micaeljtoliveira**

### CODE REVIEW

**Comment by aekiss** [comment]
is the same bug present in `check_nonadvective_mosaic`?

**Comment by micaeljtoliveira** [comment]
No, as far as I can tell, it's not, as the algorithm is written in a slightly different way.

**Comment by micaeljtoliveira** [comment]
I forgot to mention that this bug does not seem to affect the existing topography files.

**Review by russfiedler — APPROVED** [review]
Yes, this is a bug and is fixed correctly.

**Pull request merged**
